### ISSUE TITLE
Bulk unlock

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/lock-action#17]
### Feature Overview

Unlock multiple (all) keys at the same time.

### Why is the feature needed?

Sometimes we want to unlock multiple (all) keys.

### Example Code

```yaml
- uses: suzuki-shunsuke/lock@main
  with:
    mode: unlock
    key: '*' # existing all keys
    # key: '*_prod' # existing keys with the suffix `_prod`
```

### Note

- https://github.com/suzuki-shunsuke/lock-action/issues/16
