### ISSUE TITLE
Support exit with 0 even if the key has already been locked

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/lock-action#25]
### Feature Overview

Support exit with 0 even if the key has already been locked.

### Why is the feature needed?

This is useful when you ensure the key is being locked but you don't have to acquire lock in the job.

### Example Code

```yaml
- uses: suzuki-shunsuke/lock@main
  with:
    mode: lock
    key: default
    ignore_already_locked_error: true
```
