### ISSUE TITLE
Suggestion: post_unlock should only unlock its own workflow's lock(s)

### ISSUE THREAD

**Issue by SGrondin** [suzuki-shunsuke/lock-action#419]
### version

v0.1.6

### Overview

`post_unlock: true` is required in order to ensure that keys are unlocked even when jobs fail.
However, the behavior of `post_unlock` makes it unsafe to manually unlock keys early to speed deployment of multiple branches at the same time.
See the example below.

### How to reproduce

In this example:
```yaml
- name: Acquire deploy lock
  uses: suzuki-shunsuke/lock-action@v0.1.6
  with:
    mode: lock
    key: deploy
    post_unlock: true

- name: Deploy App
  # runs Terraform, etc

- name: Release deploy lock
  uses: suzuki-shunsuke/lock-action@v0.1.6
  with:
    mode: unlock
    key: deploy

- name: Do other things
  # Notifications, etc etc
```
In this example I want to release the lock as soon as possible so that other instances of this workflow can start deploying.
I'm using `post_unlock: true` because if `Deploy App` crashes, I still want to unlock the key.
The issue is that when 3+ workflows are started simultaneously, this will happen:
1. Workflow 1 (W1) locks the key
2. W2 waits for the key to be unlocked
3. W3 waits for the key to be unlocked
4. W1 unlocks the key (job: `Release deploy lock`)
5. W2 locks the key and begins deploying
6. W1 runs post_unlock and unlocks the key
7. W3 locks the key and begins deploying
8. problems happen because W2 and W3 are deploying at the same time

### Expected behaviour

`post_unlock` should only unlock keys that have been locked _by the current workflow run_.

### Actual behaviour

`post_unlock` is required in order to guarantee unlocks when deployments fail or crash.
However, `post_unlock` is not safe to use in combination with `mode: unlock`.
It can sometimes be important to manually unlock keys in order to release locks and speed up other deployments.

### Note

I don't know if this is a bug, an oversight, or intentional design.
I hope this report is useful to you.
Thank you for creating this tool.
