### ISSUE TITLE
check: Add an option to fail a job if the key is locked

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/lock-action#54]
### Feature Overview

check: Add an option to fail a job if the key is locked.

### Why is the feature needed?

This is a common use case.

### Example Code

```yaml
uses: suzuki-shunsuke/lock-action@latest
with:
  mode: check
  key: default
  fail_if_locked: "true"
```
